accountApp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountApp.views import *
# from accountApp.views import AccountCreateView, AccountDetailView, AccountUpdateView

app_name = 'accountApp'

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountApp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

gis_test_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from gis_test_1 import settings
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountApp.urls')),
    path('profile/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreationView, ProfileUpdateView

app_name = 'profileApp'

urlpatterns = [
    path('create/', ProfileCreationView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountApp/models.py
from django.db import models

# Create your models here.


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountApp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountApp.decorator import account_ownership_required
from accountApp.form.form import AccountCreationForm
from accountApp.models import HelloWorld


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountApp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountApp/detail.html'


has_ownership = [login_required, account_ownership_required]


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountApp/update.html'

    def get_success_url(self):
        return reverse('accountApp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountApp/delete.html'

accountApp/templates/accountApp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="m-5">
    <div>
        <h4>
            Sign Up
        </h4>
    </div>
    <div class="text-center mw-500 m-auto">
        <form action="{% url 'accountApp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit" class="btn btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
</div>
{% endblock %}

accountApp/templates/accountApp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="m-5">
    <div>
        <h4>
            Quit
        </h4>
    </div>
    <div class="text-center mw-500 m-auto">
        <form action="{% url 'accountApp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <div class="m-5">
                <input type="submit" class="btn btn-danger rounded-pill px-5">
            </div>
        </form>
    </div>
</div>
{% endblock %}

accountApp/templates/accountApp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            {% if target_user.profile %}
                <img class="profile_image m-4" src="{{ target_user.profile.image.url }}" alt="profile image">
                {% if target_user == user %}
                <h2 class="NNS">{{ target_user.profile.nickname }}
                    <a class="material-icons round-button" href="{% url 'profileApp:update' pk=target_user.profile.pk %}">
                        edit
                    </a>
                </h2>
                {% endif %}
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
            <h2>
                <a href="{% url 'profileApp:create' %}">
                    Create Profile
                </a>
            </h2>
            {% endif %}
        </div>
        {% if user == target_user %}
        <div>
            <a href="{% url 'accountApp:update' pk=target_user.pk %}"
             class="material-icons round-button mx-1">settings</a>
            <a href="{% url 'accountApp:delete' pk=target_user.pk %}"
             class="material-icons round-button mx-1">close</a>
        </div>
        {% endif %}
    </div>

{% endblock %}

accountApp/templates/accountApp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="m-5 mw-500 text-center m-auto">
    <div>
        <h4>
            Sign In
        </h4>
    </div>
    <div>
        <form action="{% url 'accountApp:login' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit" class="btn btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
</div>
{% endblock %}

accountApp/templates/accountApp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="m-5">
    <div>
        <h4>
            Update Info
        </h4>
    </div>
    <div class="text-center mw-500 m-auto">
        <form action="{% url 'accountApp:update' pk=user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit" class="btn btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
</div>
{% endblock %}